# Generated by Django 5.0.4 on 2024-05-02 22:04

import django.db.models.deletion
import tours.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(max_length=100)),
                ('region', models.CharField(max_length=200, verbose_name='Область/Регион')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['city', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('slug', models.SlugField()),
                ('conditions', models.TextField(verbose_name='Условия тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название тура')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='Начало тура')),
                ('end_date', models.DateTimeField(verbose_name='Конец тура')),
                ('photo', models.ImageField(blank=True, upload_to='tour/<django.db.models.fields.CharField>/%Y/%m/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_place', to='tours.place', verbose_name='Места')),
                ('tariff', models.ManyToManyField(blank=True, related_name='tour_tariff', to='tours.tariff', verbose_name='Тарифы')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TourProgramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('order', tours.fields.Odredfield(blank=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='tour/<django.db.models.fields.related.ForeignKey>/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_programm', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Программа тура',
                'verbose_name_plural': 'Программы тура',
                'ordering': ['order'],
            },
        ),
    ]
