# Generated by Django 5.0.4 on 2024-05-03 16:33

import django.db.models.deletion
import django.db.models.manager
import tours.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_is_active_alter_tour_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['id'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelManagers(
            name='tour',
            managers=[
                ('active_tours', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'Не активен'), (True, 'Активен')], default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='tourprogramm',
            name='order',
            field=tours.fields.Odredfield(blank=True, verbose_name='День(Автоматический порядок)'),
        ),
        migrations.AlterField(
            model_name='tourprogramm',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tourprogramm',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_programm', to='tours.tour', verbose_name='Тур'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-created'], name='tours_tour_created_e89256_idx'),
        ),
    ]
