# Generated by Django 5.0.6 on 2024-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tour_user_tour_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tariff',
        ),
        migrations.AddField(
            model_name='tour',
            name='places',
            field=models.ManyToManyField(related_name='tour_places', to='tours.place', verbose_name='Места проведения тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tariffs',
            field=models.ManyToManyField(blank=True, related_name='tour_tariffs', to='tours.tariff', verbose_name='Тарифы'),
        ),
    ]
