# Generated by Django 5.0.6 on 2024-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BigIntegerField(choices=[('D', 'Не активен'), ('P', 'Активен')], default='D', verbose_name='Статус'),
        ),
    ]
