# Generated by Django 5.0.6 on 2024-06-13 08:08

import django.db.models.deletion
import django.db.models.manager
import tours.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('slug', models.SlugField(blank=True)),
                ('conditions', models.TextField(verbose_name='Условия тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=200, verbose_name='Область/Регион')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['city', 'region'],
                'indexes': [models.Index(fields=['city'], name='tours_place_city_37051d_idx'), models.Index(fields=['region'], name='tours_place_region_8da8c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название тура')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало тура')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец тура')),
                ('is_active', models.BigIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=1, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, upload_to='tour/%Y/%m/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель/Организатор')),
                ('places', models.ManyToManyField(related_name='tour_places', to='tours.place', verbose_name='Места проведения тура')),
                ('tariffs', models.ManyToManyField(blank=True, related_name='tour_tariffs', to='tours.tariff', verbose_name='Тарифы')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created'],
            },
            managers=[
                ('active_tours', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('order', tours.fields.Odredfield(blank=True, verbose_name='День(Автоматический порядок)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='tour/%Y/%m/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programm', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Программа тура',
                'verbose_name_plural': 'Программы тура',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-created'], name='tours_tour_created_e89256_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-updated'], name='tours_tour_updated_0bb91d_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-start_date'], name='tours_tour_start_d_ef42cc_idx'),
        ),
    ]
