# Generated by Django 5.0.6 on 2024-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='tours_place_city_37051d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['region'], name='tours_place_region_8da8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-updated'], name='tours_tour_updated_0bb91d_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-start_date'], name='tours_tour_start_d_ef42cc_idx'),
        ),
    ]
