# Generated by Django 5.0.6 on 2024-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tour_place_remove_tour_tariff_tour_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BigIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=1, verbose_name='Статус'),
        ),
    ]
