# Generated by Django 5.0.6 on 2024-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BigIntegerField(choices=[(0, 'Не активен'), (1, 'Активен')], default=1, verbose_name='Статус'),
        ),
    ]
