# Generated by Django 5.0.6 on 2024-06-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tour_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель/Организатор'),
        ),
    ]
